version: '3.8'

services:
  cloner:
    image: alpine/git:latest
    entrypoint: [""]  # ← КЛЮЧЕВОЕ: отключаем git-entrypoint, чтобы sh/git работали нормально
    volumes:
      - workspace-data:/workspace
      - "${SSH_AUTHORIZED_KEYS:-/dev/null}:/root/.ssh/authorized_keys:ro"

    command: sh -c "rm -rf /workspace/* && git clone https://github.com/BinaryCat17/cadml.git /workspace"

  motor-pinn:
    build: .  # сборка из Dockerfile в текущей папке
    volumes:
      - workspace-data:/workspace
    working_dir: /workspace
    ports:
      - "2222:22"  # SSH на порту 2222 хоста
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 2g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    tty: true

volumes:
  workspace-data:
  