version: '3.8'

services:
  motor-pinn:
    image: nvcr.io/nvidia/physicsnemo/physicsnemo:25.11
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    working_dir: /workspace
    command: bash -c "sleep infinity"   # чтобы контейнер висел, можно было заходить
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 2g
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    tty: true
    