version: '3.8'

services:
  cloner:
    image: alpine/git
    volumes:
      - workspace-data:/workspace-git
    command: sh -c "rm -rf /workspace-git/* && git clone https://github.com/ВАШ_ЮЗЕР/ВАШ_РЕПО.git /workspace-git"

  motor-pinn:
    image: nvcr.io/nvidia/physicsnemo/physicsnemo:25.11
    depends_on:
      - cloner
    volumes:
      - workspace-data:/workspace-git  # монтируем склонированный repo
    working_dir: /workspace-git
    command: sleep infinity
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 2g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    restart: unless-stopped

volumes:
  workspace-data: