version: '3.8'

services:
  motor-pinn:
    image: nvcr.io/nvidia/physicsnemo/physicsnemo:25.11
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: bash -c "sleep infinity"  # ← контейнер не выходит, можно заходить в консоль
    ipc: host  # для SHMEM
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 2g  # для больших моделей
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped  # авторестарт при ребутах
    tty: true