version: '3.8'

services:
  cloner:
    image: alpine/git:latest
    entrypoint: [""]  # ← КЛЮЧЕВОЕ: отключаем git-entrypoint, чтобы sh/git работали нормально
    volumes:
      - workspace-data:/workspace
    command: sh -c "rm -rf /workspace/* && git clone https://github.com/BinaryCat17/cadml.git /workspace"

  motor-pinn:
    image: nvcr.io/nvidia/physicsnemo/physicsnemo:25.11
    depends_on:
      - cloner
    volumes:
      - workspace-data:/workspace
    working_dir: /workspace
    command: sleep infinity  # или python train.py, когда всё проверишь
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 2g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    restart: unless-stopped

volumes:
  workspace-data: